[Interface]
Address = 10.13.13.5
PrivateKey = qBuV3kmCv8uGkEPU9J1ad40e2c6xJCddaW+iXoc5C0A=
ListenPort = 51820
DNS = 192.168.64.254

[Peer]
PublicKey = 0rG5X75fnaMrOKrdh+FdRea7g8ghXUwrhkwjHDsYKSE=
PresharedKey = G4oPPLFbHBPSZPtcceD7wi7vbO2JqCeR1L+leSq7Cm4=
Endpoint = tars.freemyip.com:5004
AllowedIPs = 0.0.0.0/0